name: currency_picker
description: A flutter package to select a currency from a list of currencies.

homepage: https://github.com/Daniel-Ioannou
repository: https://github.com/Daniel-Ioannou/flutter_currency_picker

version: 2.0.21

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0

flutter:
  assets:
    - lib/src/res/

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0


